name: D:\program\envs\czu
channels:
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.7=py38h9128911_0
  - ca-certificates=2024.9.24=haa95532_0
  - cython=0.29.21=py38hd77b12b_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - numexpr=2.8.4=py38h7b80656_1
  - numpy-base=1.24.3=py38h8a87ada_1
  - openssl=1.1.1w=h2bbff1b_0
  - pandas=2.0.3=py38h4ed8f06_0
  - pip=24.2=py38haa95532_0
  - pyserial=3.5=py38haa95532_0
  - python=3.8.5=h5fd99cc_1
  - python-dateutil=2.9.0post0=py38haa95532_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - setuptools=75.1.0=py38haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - vc=14.40=h2eaa2aa_1
  - vs2015_runtime=14.40.33807=h98bb1dd_1
  - pip:
    - absl-py==2.1.0
    - annotated-types==0.7.0
    - ansitable==0.11.4
    - anyio==4.5.2
    - appdirs==1.4.4
    - asgiref==3.8.1
    - asttokens==2.4.1
    - attr==0.3.1
    - attrs==24.2.0
    - azure-core==1.32.0
    - azure-storage-blob==12.24.1
    - backcall==0.2.0
    - bleach==5.0.1
    - blinker==1.8.2
    - boto==2.49.0
    - boto3==1.36.21
    - botocore==1.36.21
    - boxing==0.1.4
    - cachetools==5.5.1
    - certifi==2024.8.30
    - cffi==1.17.1
    - cfgv==3.4.0
    - charset-normalizer==3.4.0
    - click==8.1.7
    - colorama==0.4.6
    - colored==1.4.4
    - comm==0.2.2
    - configargparse==1.7
    - cryptography==44.0.1
    - cycler==0.12.1
    - dash==2.18.2
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecated==1.2.18
    - distlib==0.3.9
    - distro==1.9.0
    - django==3.2.25
    - django-annoying==0.10.6
    - django-cors-headers==3.6.0
    - django-csp==3.7
    - django-debug-toolbar==3.2.1
    - django-environ==0.10.0
    - django-extensions==3.1.0
    - django-filter==2.4.0
    - django-model-utils==4.1.1
    - django-ranged-fileresponse==0.1.2
    - django-rq==2.5.1
    - django-storages==1.12.3
    - django-user-agents==0.4.0
    - djangorestframework==3.13.1
    - dlib==19.19.0
    - drf-dynamic-fields==0.3.0
    - drf-flex-fields==0.9.5
    - drf-generators==0.3.0
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - expiringdict==1.2.2
    - fastjsonschema==2.20.0
    - filelock==3.16.1
    - flask==1.1.2
    - flatbuffers==25.2.10
    - fonttools==4.55.3
    - fsspec==2024.10.0
    - google-api-core==2.24.1
    - google-auth==2.38.0
    - google-cloud-appengine-logging==1.6.0
    - google-cloud-audit-log==0.3.0
    - google-cloud-core==2.4.1
    - google-cloud-logging==3.11.4
    - google-cloud-storage==2.19.0
    - google-crc32c==1.5.0
    - google-resumable-media==2.7.2
    - googleapis-common-protos==1.67.0
    - grpc-google-iam-v1==0.14.0
    - grpcio==1.70.0
    - grpcio-status==1.70.0
    - h11==0.14.0
    - htmlmin==0.1.12
    - httpcore==1.0.7
    - httpx==0.28.1
    - humansignal-drf-yasg==1.21.10.post1
    - identify==2.6.1
    - idna==3.10
    - ijson==3.3.0
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - inflection==0.5.1
    - ipython==8.12.3
    - ipywidgets==8.1.5
    - isodate==0.7.2
    - itsdangerous==2.0.1
    - jax==0.4.13
    - jedi==0.19.2
    - jinja2==3.0.3
    - jiter==0.8.2
    - jmespath==1.0.1
    - joblib==1.4.2
    - jsonschema==3.2.0
    - jsonschema-specifications==2023.12.1
    - jupyter-core==5.7.2
    - jupyterlab-widgets==3.0.13
    - kiwisolver==1.4.7
    - label-studio==1.13.1
    - label-studio-ml==1.0.9
    - label-studio-sdk==1.0.5
    - label-studio-tools==0.0.4
    - launchdarkly-server-sdk==8.2.1
    - lockfile==0.12.2
    - lxml==5.3.1
    - machinevision-toolbox-python==0.9.7
    - markupsafe==2.1.5
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.7
    - mediapipe==0.10.11
    - ml-dtypes==0.2.0
    - mock==5.1.0
    - mpmath==1.3.0
    - mvtb-data==1.5
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.1
    - nltk==3.9.1
    - nodeenv==1.9.1
    - nose==1.3.7
    - numpy==1.24.4
    - open3d==0.18.0
    - openai==1.63.0
    - opencv-contrib-python==4.10.0.84
    - opencv-python==4.10.0.84
    - opentelemetry-api==1.30.0
    - opt-einsum==3.4.0
    - ordered-set==4.0.2
    - packaging==24.2
    - parso==0.8.4
    - pgraph-python==0.6.2
    - pickleshare==0.7.5
    - pillow==10.4.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.3.6
    - plotly==5.24.1
    - pre-commit==3.5.0
    - progress==1.6
    - prompt-toolkit==3.0.48
    - proto-plus==1.26.0
    - protobuf==3.20.3
    - psycopg2-binary==2.9.9
    - pure-eval==0.2.3
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pybullet==3.2.7
    - pycparser==2.22
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pygments==2.18.0
    - pyparsing==3.1.4
    - pyqt5==5.15.11
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.15.0
    - pyrealsense2==2.55.1.6486
    - pyrfc3339==2.0.1
    - pyrsistent==0.20.0
    - pyside6==6.6.3.1
    - pyside6-addons==6.6.3.1
    - pyside6-essentials==6.6.3.1
    - python-json-logger==2.0.4
    - python-pcl==0.3.0rc1
    - pytz==2022.7.1
    - pywin32==308
    - pyyaml==6.0.2
    - redis==3.5.3
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.32.3
    - requests-mock==1.12.1
    - retrying==1.3.4
    - robotic-arm==1.0.6
    - roboticstoolbox-python==1.1.1
    - rpds-py==0.20.1
    - rq==1.10.1
    - rsa==4.9
    - rtb-data==1.0.1
    - rules==2.2
    - s3transfer==0.11.2
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - semver==3.0.4
    - sentry-sdk==2.21.0
    - shiboken6==6.6.3.1
    - sniffio==1.3.1
    - sounddevice==0.5.1
    - spatialgeometry==1.1.0
    - spatialmath-python==1.1.13
    - sqlparse==0.5.3
    - stack-data==0.6.3
    - swift-sim==1.1.0
    - sympy==1.13.3
    - tenacity==9.0.0
    - threadpoolctl==3.5.0
    - torch==2.1.2+cu121
    - torchvision==0.16.2+cu121
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transforms3d==0.4.2
    - typing-extensions==4.12.2
    - ua-parser==0.18.0
    - ujson==5.10.0
    - uritemplate==4.1.1
    - urllib3==1.26.20
    - user-agents==2.2.0
    - virtualenv==20.28.0
    - wcwidth==0.2.13
    - webencodings==0.5.1
    - websockets==13.1
    - werkzeug==2.0.2
    - wheel==0.40.0
    - widgetsnbextension==4.0.13
    - wrapt==1.17.2
    - xmljson==0.2.1
    - zipp==3.20.2
prefix: D:\program\envs\czu
